In [74]:
%matplotlib inline
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

import sklearn
from sklearn.linear_model import LinearRegression

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

import time


In [75]:
# check if CUDA is available
use_cuda = torch.cuda.is_available()
print(use_cuda)

False


In [76]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 1)
train_csv = pd.read_csv("train.csv")
print(len(train_csv))
test_csv = pd.read_csv("test.csv")
print(len(test_csv))
samples_submission_csv = pd.read_csv("sample_submission.csv")

1460
1459


In [77]:
print(train_csv)

    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0    1          60       RL         65.0     8450   Pave   NaN      Reg   
..  ..         ...      ...          ...      ...    ...   ...      ...   

   LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0          Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
..         ...       ...       ...       ...          ...        ...   

   Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0        Norm     1Fam     2Story            7            5       2003   
..        ...      ...        ...          ...          ...        ...   

    YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0           2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
..           ...       ...      ...         ...         ...        ...   

    MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0        196.0        Gd       

In [78]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")
train_data= train_data.drop(['SalePrice'], axis='columns')
train_data= train_data.drop(['Id'], axis='columns')
test_data= test_data.drop(['Id'], axis='columns')
all_data = pd.concat([train_data, test_data], keys=["train", "test"])
all_data = pd.get_dummies(all_data)
all_data = all_data.fillna(0)
all_data = (all_data - all_data.mean()) / all_data.std()
print(all_data.shape)

train_data = all_data.loc['train']
print(train_data.shape)
test_data = all_data.loc['test']
print(test_data.shape)

train_data_target = train_csv.iloc[:,-1:]
print(train_data_target.shape)

(2919, 288)
(1460, 288)
(1459, 288)
(1460, 1)


In [80]:
reg = LinearRegression().fit(train_data, train_data_target)
reg.score(train_data, train_data_target)

0.932783471380324

In [81]:
reg.coef_

array([[-2.29269818e+03,  1.15021598e+02,  5.67121846e+03,
         9.91575547e+03,  6.47522582e+03,  9.50639275e+03,
         2.17330281e+03,  3.64538007e+03, -5.85817793e+15,
        -2.17530336e+15, -5.65225560e+15,  5.67192330e+15,
         1.15630648e+17,  1.26340005e+17,  1.36733267e+16,
        -1.49135233e+17,  7.48750000e+02, -1.72250000e+02,
         1.82481250e+03,  9.26734375e+02, -2.86437500e+03,
        -2.89662500e+03,  2.94037500e+03,  3.95350000e+03,
        -1.10330781e+04,  3.22600000e+03,  4.20021875e+03,
         1.90700000e+03,  2.02031250e+02,  4.37406250e+02,
         8.70242188e+02,  1.79706250e+03,  2.43519375e+04,
         1.86390625e+02, -9.62046875e+02, -5.53984375e+02,
        -4.11688091e+15, -9.51434366e+15, -4.19768579e+15,
        -1.86282481e+16, -1.62782314e+16,  5.21358393e+15,
         5.21358393e+15,  3.15625000e+01, -8.03750000e+01,
         5.69969615e+16,  1.92788275e+16,  8.93858759e+15,
         5.82207799e+16, -2.02571104e+16, -2.05041878e+1

In [82]:
reg.intercept_

array([1.84194916e+15])

In [83]:
reg.predict(test_data)

array([[108483.75],
       [158787.75],
       [186435.75],
       ...,
       [177411.75],
       [113795.75],
       [224899.75]])